name: Deploy to REG.RU

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./portfolio
        run: npm install

      - name: Build project
        working-directory: ./portfolio
        run: npm run _build:one
        env:
          CI: false

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./portfolio/build/
          server-dir: /www/annyraspberry.pro/
